fix: added logic and styles to confirm view
Azordev/dasher-user pull request #132
Opened 2021-11-06 12:30 UTC by denisosuna

### Description

Was added:

- the query to confirm the form
- the hook to manage the query
- the implementation of the insertRating hook
- the logic to catch the selected rating
- styles to the confirm view Page

Note: some confirm view page styles need to be fixed
fixes #43 

#### Screenshots
![image](https://user-images.githubusercontent.com/21060798/140609633-96ba7084-44d7-416b-b10e-ad94a16bcb98.png)

#### Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Go to '...'
2. Click on '....'
3. Scroll down to '....'

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

2021-11-06 13:29 UTC, elpollo12 commented
I am adding the remaining styles

2021-11-06 14:06 UTC, Katsu08 requested changes
Good job, some questions

2021-11-06 14:06 UTC, heliomar-pena commented on src/components/Rating/Rating.jsx
> +// eslint-disable-next-line react/prop-types
Theses comments are required or your have missed delete it?

2021-11-06 14:06 UTC, heliomar-pena commented on src/pages/Confirm/Confirm.jsx
> +      headerSubTitle="Inserta tus datos para finalizar Confirma recepción"
This paragraph is ok?

I ask for this part: `finalizar Confirma recepción`

2021-11-07 19:52 UTC, Israel-Laguan commented on src/components/Rating/Rating.jsx
> +// eslint-disable-next-line react/prop-types
I fixed that

2021-11-07 19:55 UTC, merged