fix: image centered
Azordev/dasher-user pull request #190
Opened 2022-01-05 16:36 UTC by ildebr

### Description

Made the MAinImage component get centered and set it to a max-height so it won't alter the layout.

fixes #187 #186

#### Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

### How to test it

If applicable, describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

1. Go to landing site
2. change the window height and width

### Checklist:

- [ ] Doesn't break the current code.
- [ ] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

2022-01-05 19:34 UTC, Israel-Laguan commented
I tested as described on the issue #187 
![image](https://user-images.githubusercontent.com/36519478/148277610-1db10d47-d25d-43a3-8beb-049e1b27e8f4.png)

I can see the same issue appearing

Regarding #186 seems like is centered

2022-01-07 23:24 UTC, Katsu08 requested changes
Not critical comment

2022-01-07 23:24 UTC, Katsu08 commented on src/pages/Home/Home.styled.jsx
> +  max-height: 410px;
Delete the line 53, the line 57 is overriding this line

2022-01-12 13:26 UTC, Katsu08 requested changes
Please add styles to fix responsive error
![imagen](https://user-images.githubusercontent.com/66505715/149148919-ba8db62e-9283-4fa5-8778-955d4ae39b4c.png)

2022-01-12 13:27 UTC, heliomar-pena reviewed
On small screens the title is hidden
![imagen](https://user-images.githubusercontent.com/66505715/149149053-ce53a4c3-b114-482f-9559-dfccac64b604.png)

The problem of the dasher user guy is fixed. Good job!
![imagen](https://user-images.githubusercontent.com/66505715/149149119-3a1d73e0-0fca-4b6e-a824-4dc65ebe65bd.png)

2022-01-13 08:06 UTC, Israel-Laguan commented on src/pages/Home/Home.styled.jsx
> +  &.images-section{
Please add space before parenthesis

2022-01-13 08:07 UTC, Israel-Laguan commented on src/pages/Home/Home.styled.jsx
>    position: relative;
Position is repeated, can you check which one is correct and erase the other one, please?

2022-01-13 08:08 UTC, Israel-Laguan commented on src/pages/Home/Home.styled.jsx
> +    margin: 0;
this overrides `margin-top` on line 83, can you verify if this is correct? If one rule is not needed please erase it

2022-01-25 13:00 UTC, Katsu08 commented
I will take this pull request to finish it

2022-01-27 06:45 UTC, Israel-Laguan commented
Tested and looks fine!

2022-01-27 06:46 UTC, Israel-Laguan approved these changes

2022-01-27 14:17 UTC, Katsu08 approved these changes

2022-01-27 17:11 UTC, e-azocar approved these changes

2022-01-27 18:02 UTC, merged