Added validation before package confirm
Azordev/dasher-user pull request #192
Opened 2022-01-11 13:25 UTC by e-azocar

### Description

I added some validations to show a message when the user tries to confirm a package already confirmed.

fixes #153 

#### Screenshots
This modal only is show when the package is already confirmed previously
![Captura de pantalla 2022-01-10 192953](https://user-images.githubusercontent.com/61360270/148949615-8695c7e2-0242-4ca8-a742-e3d7159417ba.jpg)

2022-01-11 13:42 UTC, Israel-Laguan commented on src/pages/Chat/Chat.styled.jsx
> +float: ${({ type }) => (type === 'client' ? `left` : `right`)};
Please mind the indentation

2022-01-11 13:43 UTC, Israel-Laguan commented on src/pages/Confirm/index.jsx
> +      console.log(loading)
Remove these please

2022-01-11 13:45 UTC, Israel-Laguan commented on src/pages/Confirm/index.jsx
> +      ) {
can you try something like

```js
const incompleteStatus = ['ready', 'collected', 'in_travel'];

if (incompleteStatus.includes(orderStatus)) {

```

2022-01-11 15:20 UTC, Katsu08 approved these changes
I see good the code. But i don't know how I can test the page
![imagen](https://user-images.githubusercontent.com/66505715/148970321-15910627-3bc1-4a25-9f65-e638fa44ba6f.png)

2022-01-11 15:42 UTC, Katsu08 requested changes
A little change

2022-01-11 15:42 UTC, Katsu08 commented on src/pages/Confirm/index.jsx
>        }
Add validation "El paquete y el RUT no concuerdan"

2022-01-11 17:59 UTC, Israel-Laguan approved these changes

2022-01-11 20:00 UTC, Katsu08 approved these changes
I see it good

![image](https://user-images.githubusercontent.com/66505715/149012077-8cf82977-589b-4725-8cef-d4d8ae30d106.png)

![image](https://user-images.githubusercontent.com/66505715/149012204-6095fd48-706b-47e8-a58a-4bfe37723c78.png)

But I think that at the first error (El RUT y el Id del paquete no coinciden, o el paquete no existe), the user doesn't should be redirected. Because what if is a common client that wrote wrong the RUT, and the page redirect he to other page and don't know how to come back to the confirm page?

Or what do you think @angelik0828

2022-01-12 16:14 UTC, Katsu08 approved these changes
Thanks for the changes

2022-01-12 18:10 UTC, merged