Feat/kn/add map layout component #33
Azordev/dasher-user pull request #78
Opened 2021-10-08 02:51 UTC by Saikilito

![image](https://user-images.githubusercontent.com/29690711/136490676-c7802ce0-f2b9-43fe-b4be-d212843ae5f7.png)

![image](https://user-images.githubusercontent.com/29690711/136490698-d413c94e-0d23-49fc-aa79-bd6cfc39937d.png)

/test

2021-10-08 02:53 UTC, Israel-Laguan commented on package.json
> +    "typescript": "^4.4.3",
@ginnaaceror please confirm if you are OK with using typescript

2021-10-08 03:02 UTC, Israel-Laguan requested changes
Also, why did you erase these files? 
![image](https://user-images.githubusercontent.com/36519478/136491242-f439874f-1a90-48de-8998-e19559d0a73c.png)

These are needed in the remaining file so its breaking the app.

Also you didn't include images in `src/asset` back or forgot to add to commit, please check
![image](https://user-images.githubusercontent.com/36519478/136491661-5281be83-a4e6-4946-9c2b-7d6e1718d7bf.png)

2021-10-08 03:02 UTC, Israel-Laguan commented on src/pages/index.js
> +        <Test />
please remove this debugging artifact

2021-10-08 03:02 UTC, Israel-Laguan commented on src/pages/index.js
> +import Test from './TEST'
please remove this debugging artifact

2021-10-08 03:02 UTC, Israel-Laguan commented on package.json
> +    "tslint": "^6.1.3"
`tslint` is deprecated, please not use it
![image](https://user-images.githubusercontent.com/36519478/136491454-f381ed40-3b78-4de5-9507-67ad909dd44b.png)

reference: https://www.infoq.com/news/2019/02/tslint-deprecated-eslint/#:~:text=Palantir%2C%20the%20creators%20of%20TSLint,linting%20solution%20for%20TypeScript%20users.

2021-10-08 03:04 UTC, Israel-Laguan commented
I don't see css code for Layout, please check or commit unstaged changes @Saikilito

2021-10-08 16:22 UTC, Saikilito commented
@Israel-Laguan  make sure you have the folder with the full name, the items were not deleted just renamed.

2021-10-08 16:34 UTC, Saikilito commented on src/pages/index.js
> +import Test from './TEST'
removed

2021-10-08 17:06 UTC, Israel-Laguan commented on src/layouts/map.layout.tsx
> +// TODO: the spelling gives problems with spanish
Just add Spanish to the available languages by using an extension

https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker-spanish

2021-10-08 17:06 UTC, Israel-Laguan commented on .prettierrc.js
> +  semi: true,
why?

2021-10-08 17:06 UTC, Israel-Laguan commented on cspell.config.json
> +    ".git/**"
Good finding, what problems this was doing?

2021-10-08 17:06 UTC, Israel-Laguan commented on package.json
> +    "lint:css": "stylelint --config .stylelintrc.json './**/*.styled.tsx'; echo 'CSS fine! 💅'",
just add the extension by using regex please, like this:

`src/**/*.{js,jsx,ts,tsx}`

2021-10-08 17:06 UTC, Israel-Laguan commented on src/layouts/components/MapUpperBar/MapUpperBar.style.tsx
> +  background-color: ${colors.default.blue08};
what about `var(--primary);`? Please try it

2021-10-08 17:21 UTC, Saikilito commented on .prettierrc.js
> +  semi: true,
the types and interface for typescript require ";" the final of the line

2021-10-08 18:08 UTC, Israel-Laguan commented on .prettierrc.js
> +  semi: true,
Ok, got it, thanks for explain

2021-10-08 18:35 UTC, Saikilito commented on cspell.config.json
> +    ".git/**"
it backs

2021-10-08 18:54 UTC, Saikilito commented
This branch iss squashed

2021-10-08 19:02 UTC, Israel-Laguan requested changes

2021-10-08 19:02 UTC, Israel-Laguan commented on src/layouts/components/MapLowerBar/MapLowerBar.tsx
> +          <div style={{ display: 'flex', width: '100%', justifyContent: 'space-evenly', alignItems: 'center' }}>
This one have too much inline styles, please make it a Component using styled components

2021-10-08 19:02 UTC, Israel-Laguan commented on src/layouts/components/MapLowerBar/MapLowerBar.tsx
> +          <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', padding: '1rem' }}>
This one have too much inline styles, please make it a Component using styled components

2021-10-08 19:02 UTC, Israel-Laguan commented on src/layouts/components/MapUpperBar/MapUpperBar.tsx
> +      <div style={{ display: 'flex', alignItems: 'center', color: 'white' }}>
This one have too much inline styles, please make it a Component using styled components

2021-10-08 19:02 UTC, Israel-Laguan commented on src/styles/text.ts
> +  `,
Please be aware these were fixed in Ginna's PR, [HERE](https://github.com/Azordev/dasher-user/blob/e41aa0b119f4dbf679e971a389a88c14e56f7e83/src/styles/text.js).

Change it to be like these

2021-10-08 19:02 UTC, Israel-Laguan commented on src/styles/text.ts
> +  test: 'color: red;',
Remove this line please

2021-10-08 19:03 UTC, Saikilito commented on src/styles/text.ts
> +  `,
this change is only prettier

2021-10-08 19:06 UTC, Israel-Laguan commented on src/styles/text.ts
> +  `,
No, look that name of variable doesn't includes 'dasher'. I am asking you to update your code according to the correct names, can you do it?

2021-10-08 19:54 UTC, Saikilito commented on src/styles/text.ts
> +  test: 'color: red;',
removed

2021-10-08 20:09 UTC, Israel-Laguan commented on src/components/index.tsx
> +export * from './Container';
I checked and Container is not in components, can you check, please?
![image](https://user-images.githubusercontent.com/36519478/136619337-e86d1b38-69eb-46a0-8a28-94bd5d1d2bbd.png)

2021-10-08 20:10 UTC, Israel-Laguan commented on src/components/index.tsx
> +export * from './Container';
This is breaking the app

2021-10-08 21:05 UTC, Saikilito commented on src/components/index.tsx
> +export * from './Container';
resolved

2021-10-08 21:14 UTC, Israel-Laguan commented on src/pages/Delivery.jsx
>      <div>
Please include here the layout you just created so we can test @Saikilito

2021-10-08 21:17 UTC, Israel-Laguan commented on src/pages/Delivery.jsx
>      <div>
Currently looks like this
![image](https://user-images.githubusercontent.com/36519478/136625717-c3544022-81d4-422f-8491-5211b0fad3f3.png)

2021-10-09 00:16 UTC, Saikilito commented on src/pages/Delivery.jsx
>      <div>
included

2021-10-10 00:37 UTC, Israel-Laguan commented on README.md
> +| [Kembert Nieves][author-github] | ![email-icon][] Email me to [contact@kembertnieves.com][author-email] / ![linkedin-icon][] Connect to [my Linkedin][author-linkedin] |
Linkedin link is showing my profile, please update

2021-10-10 00:38 UTC, Israel-Laguan commented on README.md
> +| ![author-pic][] | ![banner][] |
Photo is mine, please update. Also banner have my name

2021-10-10 00:38 UTC, Israel-Laguan commented on package.json
> +    "typescript": "^4.4.3",
@ginnaaceror can you try on your pc please?

2021-10-10 00:50 UTC, Israel-Laguan commented on src/layouts/components/MapLowerBar/MapLowerBar.styled.tsx
> +    width: 105%;
why is bigger than 100%?

2021-10-11 14:28 UTC, ginnaaceror approved these changes

2021-10-11 14:28 UTC, ginnaaceror commented on package.json
> +    "typescript": "^4.4.3",
I prefer ES6.

2021-10-11 14:28 UTC, ginnaaceror commented on package.json
> +    "typescript": "^4.4.3",
Hi @Israel-Laguan I can see it well on my pc.

2021-10-11 14:28 UTC, ginnaaceror commented on package.json
> +    "typescript": "^4.4.3",
finally we are going to use TS or ES6?

2021-10-11 14:28 UTC, ginnaaceror commented on src/components/Container/EvenlyContainer.tsx
> +
hi @Saikilito on line 7 why are you leaving this space?  ***it's curiosity :)***

2021-10-12 13:26 UTC, closed without merging