feature/#26-add-form-component
Azordev/dasher-user pull request #92
Opened 2021-10-13 01:49 UTC by AlejandroSalcido

### Description

Form Component enhanced re usability, react context basic usage in order to handle with form inputs actions and values.

#### Type of change

- [x] New feature (non-breaking change which adds functionality)

### How to watch it:
Search into the github branches and select the one named: 'feature/#26-add-form-component', once there fetch and pull in order to update the code. Lastly use the command you use to initialize the app ant check how the form look on the home ' / ' page

### Checklist:

- [x] Doesn't break the current code.
- [x] Passes linters and test, also is building.
- [ ] Doesn't have spelling or grammatical problems.
- [ ] Doesn't have unnecessary comments or debugging code.
- [ ] The branch is updated with the last dev branch changes.

2021-10-13 06:59 UTC, Israel-Laguan requested changes
Please remade this whole component. Remember this should be reusable and composable.

Also add an example of use.

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +const Form = () => {
please add props like onSubmit, action, target and validation

Reference: https://www.w3schools.com/html/html_forms_attributes.asp

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +const FormWrapper = styled.div`
should use styled.form

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +    background: yellow;
this style is not needed, should be none or transparent

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +  height: 100vh;
this is not good, should be 100%

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +`
this is not needed

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +      <Button>confirmar</Button>
this is not needed

2021-10-13 06:59 UTC, Israel-Laguan commented on src/components/Form.jsx
> +import Input from '../components/Input'
this is not needed

2021-10-14 07:31 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +  height: 100vh;
Corrected

2021-10-14 08:25 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +    background: yellow;
Done

2021-10-14 08:26 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +`
minimal fixes done

2021-10-14 08:28 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +      <Button>confirmar</Button>
So form would be only a list of multiple input, no button?

2021-10-14 08:30 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +const FormWrapper = styled.div`
div changed to a form!

2021-10-14 08:32 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +import Input from '../components/Input'
if input is not going to be recycled here, form would be a 3 input reusable component, or how we are going to hadle it?

2021-10-14 09:48 UTC, AlejandroSalcido commented on src/components/Form.jsx
> +const Form = () => {
hadeled submit inside the form

2021-10-14 10:16 UTC, Israel-Laguan commented on src/components/Form.jsx
> +      <Button>confirmar</Button>
Maybe the buttons can be part of the form component. About Input we can just make them children in this case. we can check this case in a meeting later to clarify.

2021-10-29 13:33 UTC, Israel-Laguan requested changes
Good job with the provider method! Just few things and we can merge

2021-10-29 13:33 UTC, Israel-Laguan commented on src/pages/Home.jsx
> +    <Form>
You forgot a onSubmit event here, also manage errors, but is OK for now.

Just include onSubmit and we can merge

2021-10-29 13:33 UTC, Israel-Laguan commented on src/components/Form.jsx
> +  const { children } = props
this is not needed, move this to line 10, like:

`const Form =({ children, onSubmit }) => {`

2021-10-29 13:33 UTC, Israel-Laguan commented on src/components/Form.jsx
> +  children: PropTypes.any,
Please avoid using any. In this case for example use `PropTypes.node`

2021-10-29 19:50 UTC, Israel-Laguan commented
Please rebase

2021-10-30 15:01 UTC, Israel-Laguan commented
If I want to get data from a parent component I notice there is no way

2021-11-02 04:33 UTC, denisosuna commented
> If I want to get data from a parent component I notice there is no way
> 
> in Check I was trying to get the value of packageCode before checking with modal, but your implementation makes it difficult. Please explore other way

I have made some changes to solve this, I think it works fine, please check

2021-11-02 04:50 UTC, Israel-Laguan commented
I see this error on console 
![image](https://user-images.githubusercontent.com/36519478/139788561-f7a63873-ed64-4649-9afc-add933412d18.png)

2021-11-02 23:18 UTC, denisosuna commented
> I see this error on console ![image](https://user-images.githubusercontent.com/36519478/139788561-f7a63873-ed64-4649-9afc-add933412d18.png)

this error should be solve, please check @Israel-Laguan

2021-11-03 17:47 UTC, Israel-Laguan approved these changes

2021-11-03 17:48 UTC, Israel-Laguan commented
Tested again and

2021-11-03 17:48 UTC, merged