Feature/#33 add map layout component
Azordev/dasher-user pull request #99
Opened 2021-10-20 14:13 UTC by elpollo12

### Description

Added map layout with styled components.

fixes # (issue)

#33 

#### Screenshots
![scrnli_20_10_2021 10-11-06](https://user-images.githubusercontent.com/7535800/138109635-e09b6565-0fec-4b54-89d7-be4e621a08c6.png)

2021-10-20 14:46 UTC, Israel-Laguan requested changes

2021-10-20 14:46 UTC, Israel-Laguan commented on src/pages/index.js
> +      </Route>
This route  changed to `delivery`. Please move the implementation to Delivery and erase this new route

2021-10-20 14:48 UTC, Israel-Laguan commented on src/pages/index.js
> +      </Route>
Also a layout should be used inside the Page

2021-10-20 14:50 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +    width: 80%;
If you use relative or dynamic with, please include min-width and max-width

2021-10-20 14:50 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +  width: 50%;
If you use relative or dynamic with, please include min-width and max-width

2021-10-20 14:51 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +    margin: 0 10%;
The relative margin on widescreen looks weird, please verify on widescreens

2021-10-20 14:52 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +  padding: 5% 0;
The relative margin on widescreen looks weird, please verify on widescreens and in mobile

2021-10-20 14:52 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +  height: 20%;
If you use relative or dynamic height, please include min-height and max-height

2021-10-20 14:53 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +  }
why not inside the div?

2021-10-20 14:53 UTC, Israel-Laguan commented on src/components/Map/Map.styled.jsx
> +  }
Why not inside the div

2021-10-21 16:00 UTC, elpollo12 commented
Updated code.

2021-10-21 16:35 UTC, elpollo12 commented on src/pages/index.js
> +      </Route>
Can I replace the complete content in delivery

2021-10-21 21:41 UTC, Israel-Laguan commented on src/pages/index.js
> +      </Route>
yes

2021-10-22 11:19 UTC, elpollo12 commented
I have updated the code. Now the map should fit the available space and avoid scrolling @Israel-Laguan @AlejandroSalcido

2021-10-22 13:24 UTC, Israel-Laguan approved these changes
Lets face other fixes in other tickets

2021-10-22 13:24 UTC, merged